### ISSUE TITLE
How do I control the robot using my laptop keyboard?

### ISSUE THREAD

**Issue by bensontran** [ms-iot/build2015-robot-kit#12]
How do I run the application on my Window 10 laptop instead of on the raspberry pi itself so I can control the robot via my pc?

**Comment by ooeygui** [comment]
Hi There,
For this scenario, there are a number of ways to approach this, depending on what you are interested in. 

The [Robot Kit](http://microsoft.hackster.io/windowsiot/robot-kit) project implements a network based control solution.

I'd recommend looking at [AllJoyn for Windows 10](http://ms-iot.github.io/content/win10/samples/AllJoynSamples.htm) to expose a driving interface, then write an app on the desktop to control it.

Lou
