### ISSUE TITLE
What version of Visual Studio will open this .csproj file?

### ISSUE THREAD

**Issue by buchannon** [ms-iot/build2015-robot-kit#9]
I feel stupid for asking this, but what version of windows/VS should I be using to open the RoboApp project in this solution?  I've tried VS 2012, 2013, and 2015 community editions, on windows 7, windows 8, and even windows 10 preview. Every time I get a message saying that the project is unsupported.

I assumed VS 2015 community running on windows 10 would open it because I see these settings in the .csproj file.
TargetPlatformVersion = 10.0.10069.0
MinimumVisualStudioVersion = 14

Thank you!

**Comment by ghost** [comment]
I had this problem until I noticed my VS 2015 install did not have the Universal Windows App Development Tools installed.  Change/Modify your installation and make sure this is installed.

**Comment by buchannon** [comment]
Thanks Brian - here is the link for anyone else reading.
https://dev.windows.com/en-us/downloads/install-dev-tools-visual-studio-2015 

I installed that, then enabled developer mode on my device, then got stuck with another error "you must update visual studio to load this project" that gets stuck. Sigh. I will go with another solution.

**Comment by tommykdev** [comment]
I could not repro your issue.

The Development OS should be 10074 or later of the Windows 10 Preview release.
The Visual Studio 2015 version should be 14.0.228823.1 D14REL or later.

Make sure to follow the steps at http://ms-iot.github.io/content/win10/SetupPC.htm, especially the part about ensuring that the 'Universal Windows App Development Tools' are installed.

Check any of the known issues at https://social.msdn.microsoft.com/Forums/en-US/home?forum=Win10SDKToolsIssues in case your symptom matches those.
